[package]
name = "fr-simd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "SIMD primitives — base64, fast UTF-8, etc."

[lib]
path = "src/lib.rs"

[dependencies]
base64-simd.workspace = true
simdutf8.workspace = true
thiserror.workspace = true
